### ISSUE TITLE
+14632214194 is treated as non-valid number

### ISSUE THREAD

**Issue by manoj2292** [hodgepodgers/ng-intl-tel-input#108]
hello, +14632214194 is treated as non-valid number. please verify.

**Comment by manoj2292** [comment]
Hi, Any updates in this issue ?

**Comment by manoj2292** [comment]
still not !!

**Comment by jrthib** [comment]
This library is using an out of date google lib phone number version. Once updated these numbers might validate.

**Comment by manoj2292** [comment]
Thanks for replying, and how much time it will take to update any idea??

**Comment by jrthib** [comment]
Not sure. Someone will need to create a pull request with the upgrade included and hopefully the owner of this repository will accept and release it.

**Comment by manoj2292** [comment]
Thanks joseph, please update on email once  done.

**Comment by jrthib** [comment]
Are you making the pull request?

**Comment by bighappyface** [comment]
The later versions of the google lib phone stuff removes the formatter but should improve validation coverage.

We (maintainers) have not had many validation issues to drive the updates. PRs are welcome.
