### ISSUE TITLE
Some Indian numbers (+91 87(8) *** ****, +91 832 (0)** **** ) are treated as invalid.

### ISSUE THREAD

**Issue by nidhi95** [hodgepodgers/ng-intl-tel-input#113]

**Comment by gprathuish** [comment]
there is a utils.js (https://github.com/jackocnr/intl-tel-input/blob/master/build/js/utils.js) file in the jackocnr/intl-tel-input git. Update that file with your local file. Or load the utils.js file externally.
angular.module('app',[ 'internationalPhoneNumber' ]).
config(function(ipnConfig){
ipnConfig.utilsScript = "downloaded utils.js file location"
})
