### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by jrthib** [hodgepodgers/ng-intl-tel-input#114]
I’ve found several bugs that exist and am hoping to submit PRs to fix them.

**Comment by adamreisnz** [comment]
I wouldn't count on it, the last commit was more than a year ago.
I might fork the module and refactor it/clean it up and then release as a [Meanie](https://github.com/meanie/angular-seed) Angular module.

**Comment by jrthib** [comment]
I’d be up for helping with that

**Comment by bighappyface** [comment]
PRs are welcome. Please read the contributing document for guidelines.

**Comment by jrthib** [comment]
Ok great! Just checking before investing time in this module.

**Comment by adamreisnz** [comment]
@jrthib I'll ping you here once my fork is live and if you want to help you're more than welcome 👍
