### ISSUE TITLE
Missing flags in grunt build

### ISSUE THREAD

**Issue by pattinsont** [hodgepodgers/ng-intl-tel-input#23]
The issue appears to be that the flag images are not present in the production site (post grunt build), but are available in the development site (grunt serve, for example). This might be related to missing bower statements, requiring manual css stylesheet and js inclusion in index.html:

    <link rel="stylesheet" href="bower_components/intl-tel-input/build/css/intlTelInput.css" />
    
    <script src="bower_components/intl-tel-input/build/js/intlTelInput.min.js"></script>
    <script src="bower_components/intl-tel-input/lib/libphonenumber/build/utils.js"></script>
    <script src="bower_components/ng-intl-tel-input/ng-intl-tel-input.module.js"></script>
    <script src="bower_components/ng-intl-tel-input/ng-intl-tel-input.provider.js"></script>
    <script src="bower_components/ng-intl-tel-input/ng-intl-tel-input.directive.js"></script>
Development:
![development](https://cloud.githubusercontent.com/assets/4594389/9404560/9b6b9a9c-47e8-11e5-96d1-33ab02ac52b4.PNG)
Production:
![production](https://cloud.githubusercontent.com/assets/4594389/9404506/333fc696-47e8-11e5-9f56-830969b00db8.PNG)

**Comment by bighappyface** [comment]
@pattinsont check out step three of _intl-tel-input_ [Getting Started](https://github.com/Bluefieldscom/intl-tel-input/blob/master/README.md#getting-started)

In the samples you provided, is the production sample public?

**Comment by bighappyface** [comment]
@pattinsont any updates?

**Comment by SruthySur** [comment]
@bighappyface, great.
That helped ! Thanks
