### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by markus138** [hodgepodgers/ng-intl-tel-input#27]
can I and if yes, how can I use this lib with browserify?

**Comment by bighappyface** [comment]
@markus138 are you using Browserify to bring in Angular?

**Comment by markus138** [comment]
yes, I tried requiring ng-intl-tel-input like all other modules, but got undefined

**Comment by bighappyface** [comment]
Are you also using any other Angular modules like UI router, ngMessages, or something like that?

**Comment by markus138** [comment]
yes, ui routes, ngMessages and some other of the standard angular modules

**Comment by bighappyface** [comment]
Please post a snippet of the code where you are using `require` for those angular modules and attempting to `requires` this module.

**Comment by SyntaxStacks** [comment]
@markus138 we currently do not support browserify out of the box. 
Please see https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes#packagejson-4 for direction on how to shim this dependency into browserify. 

Personally I'd love to see a contribution for this, I use browserify as well :]

**Comment by markus138** [comment]
thank you for your answers. In the last days I managed to integrate intl-tel-input into my angular project without using this directive. Since I'm not very happy with my current solution I'll probably be back and take a closer look on how to integrate this module with broserify

**Comment by mp3il** [comment]
Any plans on supporting browserify?

**Comment by SyntaxStacks** [comment]
@mp3il There are no plans to support browserify, but https://github.com/hodgepodgers/ng-intl-tel-input/issues/27#issuecomment-139245624 explains how you can use `browserify-shim` to include this directive.
