### ISSUE TITLE
Fix bower.json

### ISSUE THREAD

**Issue by vogloblinsky** [hodgepodgers/ng-intl-tel-input#28]
Hi,

Could you please fix your bower.json from that :
"main": "src/ng-intl-tel-input.directive.js",
to that :
"main": "dist/ng-intl-tel-input.directive.js"

The lib breaks with tools like wiredep.

Thanks

**Comment by bighappyface** [comment]
@vogloblinsky PRs are welcome :wink: 

We are more receptive to contributions than orders.

**Comment by vogloblinsky** [comment]
Submitted ;)

**Comment by SyntaxStacks** [comment]
https://github.com/hodgepodgers/ng-intl-tel-input/pull/29
