### ISSUE TITLE
Support type="tel" for mobile browsers

### ISSUE THREAD

**Issue by shenlong** [hodgepodgers/ng-intl-tel-input#41]
This directive does not support type="tel" which fires the keypad keyboard.

Modify the following to fix this:

    angular.module('ngIntlTelInput')
    .directive('ngIntlTelInput', ['ngIntlTelInput', '$log',
      function (ngIntlTelInput, $log) {
        return {
          restrict: 'A',
          require: 'ngModel',
          link: function (scope, elm, attr, ctrl) {
            // Warning for bad directive usage.
            if ((attr.type !== 'tel' && attr.type !== 'text') || elm[0].tagName !== 'INPUT') {
              ...
            }
          }

**Comment by shenlong** [comment]
pull request is here:
https://github.com/hodgepodgers/ng-intl-tel-input/pull/42

**Comment by bighappyface** [comment]
Closed with #51
