### ISSUE TITLE
Support text input with no type="text" declerations

### ISSUE THREAD

**Issue by avif** [hodgepodgers/ng-intl-tel-input#44]
Text inputs without type="text" deceleration are not treated as valid inputs.

Reason:
* Browsers set inputs without type deceleration to "input" by default.
* Minifiers often drop type="text" decelerations.

Example:
```html
<input name="tel" ng-model="tel" ng-intl-tel-input>
```

**Comment by bighappyface** [comment]
Closed with https://github.com/hodgepodgers/ng-intl-tel-input/pull/46
