### ISSUE TITLE
country data

### ISSUE THREAD

**Issue by Karthickgreets99** [hodgepodgers/ng-intl-tel-input#48]
i want to get country code and country name from the input filed.

i am trying like this , but no luck
expect(element.intlTelInput('getSelectedCountryData').iso2).toEqual('gb');

**Comment by bighappyface** [comment]
Be sure to follow this example test closely:

https://github.com/hodgepodgers/ng-intl-tel-input/blob/e7cf4c76c36b0e88e32e6718440c5b5934d50684/ng-intl-tel-input.directive.spec.js#L82-L92
