### ISSUE TITLE
Unable to validate mobile numbers 

### ISSUE THREAD

**Issue by ChhabraAnkur** [hodgepodgers/ng-intl-tel-input#49]
We are using angular version 1.2 and the whole solutions is dependent on 1.2. We want to implement ng-intl-tel-input but getting this error.

Error: ctrl.$validators is undefined
/lib/ng-intl-tel-input/ng-intl-tel-input.directive.js:20:11

If we commit the conflicted code then we are unable to validate the numbers.
Please reply ASAP.

**Comment by bighappyface** [comment]
@ChhabraAnkur we are sorry, but this module is only available for Angular 1.4.x+.

That is the cause of the error you are encountering: https://code.angularjs.org/1.4.8/docs/api/ng/type/ngModel.NgModelController (search for "$validators")
