### ISSUE TITLE
Inconsistent formatting when input is dynamically set

### ISSUE THREAD

**Issue by shenlong** [hodgepodgers/ng-intl-tel-input#52]
Hi Guys,

When you click the flag and input the phone number, the format is shown as {flag}{phone number}.
But when we dynamically set the value, the format is {flag}{+dial code}{phone number} 

Any workaround for it?
Demo here:
https://plnkr.co/edit/J3b8Z8KBHIoLBQ7QLrnb?p=preview

Btw, the example index.html has the title wrong for the component. it is ng-intl, not ng-intel !!!

**Comment by deanmono** [comment]
Also running into this issue. It's not pretty but maybe throw a filter on top to format dynamically?

**Comment by deanmono** [comment]
So theres a flag that needs to be set in the config... nationalMode: false

**Comment by shenlong** [comment]
@deanmono , it is not working. I have added

`ngIntlTelInputProvider.set({
      nationalMode: true
    });`

Refer to updated example:
https://plnkr.co/edit/J3b8Z8KBHIoLBQ7QLrnb?p=preview

I thought default for nationalMode = true ?

**Comment by deanmono** [comment]
@shenlong I've switched over to [betsol/ng-intl-tel-input](https://github.com/betsol/ng-intl-tel-input) with better results
