### ISSUE TITLE
Filter for displaying

### ISSUE THREAD

**Issue by robin-thoni** [hodgepodgers/ng-intl-tel-input#53]
Hi,
I noticed that there's no filter for displaying formatted phone number outside an input. Here's what I did, maybe someone with more knowledge of intlTelInput could do something better:

```
.filter('phoneNumber', [function() {
        var odv = $(document.createElement("input"));
        odv.intlTelInput();
        /**
         * numberFormat = ["E164", "INTERNATIONAL", "NATIONAL", "RFC3966"]
         */
        return function(input, numberFormat)
        {
            if (numberFormat == null) {
                numberFormat = "NATIONAL";
            }
            odv.val("+" + input);
            return odv.intlTelInput("getNumber", intlTelInputUtils.numberFormat[numberFormat]);
        };
    }])
```

**Comment by sultanrbt** [comment]
This filter is having an issue, we are not able to delete or modify the number its is not allowing backspaces

**Comment by robin-thoni** [comment]
What do you mean by 'delete or modify the number' ? The aim the just to display a number without an input, like `<span>{{ mynumber | phoneNumber }}</span>`

**Comment by bighappyface** [comment]
Formatting has been removed from https://github.com/jackocnr/intl-tel-input as of v8.0.0 and we are updating to v9.0.0 in #61.
