### ISSUE TITLE
How to differentiate country code and phone number from model 

### ISSUE THREAD

**Issue by sultanrbt** [hodgepodgers/ng-intl-tel-input#55]
Hi I have installed this and its very good work i appreciate it, I was just digging into it,
I was wondering just how to differentiate country code and phone number from the model
any help is greatly appreciated.
Awaiting your reply.

**Comment by bighappyface** [comment]
Will be addressed with https://github.com/hodgepodgers/ng-intl-tel-input/pull/62

**Comment by bighappyface** [comment]
Closed with #62
