### ISSUE TITLE
Double digit on windows phone 10

### ISSUE THREAD

**Issue by manjoker** [hodgepodgers/ng-intl-tel-input#60]
Hi every body, can you tell me why on windows phone 10 when i want enter phone number i always have double digits. 
on ios, android, pc, mac i don't have this problem but problem arrive only windows phone 10 with edge.

Thank for your help or your answer.

**Comment by bighappyface** [comment]
@manjoker I am not sure but we are working on an update in #61 that has major updates to https://github.com/jackocnr/intl-tel-input that may solve the issue.

**Comment by manjoker** [comment]
@bighappyface Thank a lot for your answer and wait the update.

Have a nice day.

**Comment by bighappyface** [comment]
@manjoker I have rolled v2.0.0. Be aware that there are distinct BC breaking changes.
