### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kotmatpockuh** [hodgepodgers/ng-intl-tel-input#64]
Build **ddbb11a29e7c5c0516890f67fbd16bacaea37e8f** is invalid...

**Comment by bighappyface** [comment]
Details?

**Comment by kotmatpockuh** [comment]
https://travis-ci.org/hodgepodgers/ng-intl-tel-input

**Comment by kotmatpockuh** [comment]
#156 failed

**Comment by bighappyface** [comment]
Good catch. The previous commit is passing so that last change in #56 is clearly the issue.

**Comment by kotmatpockuh** [comment]
by the way: utils.js won't work with angularJS 1.5

**Comment by bighappyface** [comment]
The latest build for 2.0.0 is passing. It has the updated `utils.js` but I have not tested it out with Angular 1.5 yet.

https://travis-ci.org/hodgepodgers/ng-intl-tel-input/builds/166236229
