### ISSUE TITLE
[Suggestion] Create Npm version

### ISSUE THREAD

**Issue by aviadhahami** [hodgepodgers/ng-intl-tel-input#68]
Hey 
We've all noticed that `bower` is losing its popularity for the better use of `npm`. 
I think that porting a version of this module as `npm` dependency would  be nice :) 

What do you think?

**Comment by skfd** [comment]
It's on there -- [ng-intl-tel-input](https://www.npmjs.com/package/ng-intl-tel-input).

**Comment by aviadhahami** [comment]
@skfd god bless you sir.

Will PR the readme
