### ISSUE TITLE
Bad example attribute data-default-country

### ISSUE THREAD

**Issue by krystiankoper** [hodgepodgers/ng-intl-tel-input#73]
This is wrong sample:
`<input type="text" ng-model="model.tel" ng-intl-tel-input data-default-country="gb">`

After I saw you code inside directive it should be:
`<input type="text" ng-model="model.tel" ng-intl-tel-input initial-country="gb">`

**Comment by imbdb** [comment]
I created a pull request with updated(Corrected) Readme
#72

**Comment by bighappyface** [comment]
Resolved by #72
