### ISSUE TITLE
 Validations should stop misfiring after entering in correct phone number format

### ISSUE THREAD

**Issue by sultanmd89** [hodgepodgers/ng-intl-tel-input#89]
Hi,
I am entering **valid phone numbers** its throwing invalid error.
**How to add those can you please suggest**

**Please suggest.**

![phonenumbervalidation2](https://cloud.githubusercontent.com/assets/20988937/22094791/f2390ffa-de35-11e6-90f7-b625ce7ff11f.png)

Attaching screenshot for reference.
![phonenumbervalidation](https://cloud.githubusercontent.com/assets/20988937/22094800/0d491c04-de36-11e6-8143-34f8d985da1a.png)

**Comment by sultanmd89** [comment]
Please answer on this. I am awaiting reply on this

**Comment by feraudet** [comment]
+1

**Comment by bighappyface** [comment]
@sultanmd89 @feraudet this library uses another library for validation. This package is strictly the an angular facility for the other library.

Using the validation demo for the other library I see that the number in the example is marked as invalid there too. That is why it is invalid on our demo as well.

http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
